/**:
  ros__parameters:
    common:
      img_en: 1
      img_topic: /camera/image_color
      imu_topic: /livox/imu
      lid_topic: /demo/slam/lidar_filtered
      lidar_en: 1
      require_complete_imu: false
      ros_driver_bug_fix: false
      use_gps: false
    debug:
      sensor_sync_diagnostics: true
    evo:
      pose_output_en: false
      seq_name: Go2_Multifloor_LIVO
    extrin_calib:
      Pcl:
      - -0.0
      - -0.0177
      - -0.08
      Rcl:
      - 0.0
      - -1.0
      - 0.0
      - 0.0
      - 0.0
      - -1.0
      - 1.0
      - 0.0
      - 0.0
      extrinsic_R:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      extrinsic_T:
      - 0.2
      - 0.0
      - 0.1177
    image_save:
      img_save_en: false
      interval: 1
    imu:
      acc_cov: 0.2
      b_acc_cov: 0.001
      b_gyr_cov: 0.001
      gyr_cov: 0.05
      imu_en: true
      imu_int_frame: 300
    lio:
      beam_err: 0.05
      dept_err: 0.02
      layer_init_num:
      - 5
      - 5
      - 5
      - 5
      - 5
      max_iterations: 5
      max_layer: 2
      max_points_num: 50
      min_eigen_value: 0.005
      voxel_size: 0.5
    local_map:
      half_map_size: 100
      map_sliding_en: false
      sliding_thresh: 8.0
    pcd_save:
      colmap_output_en: false
      filter_size_pcd: 0.15
      interval: 200
      pcd_save_en: false
      type: 0
    preprocess:
      blind: 0.3
      filter_size_surf: 0.15
      lidar_type: 0
      point_filter_num: 1
      scan_line: 32
    publish:
      base_frame: base
      blind_rgb_points: 0.0
      dense_map_en: true
      pub_effect_point_en: false
      pub_plane_en: false
      pub_scan_num: 1
      publish_base_tf: false
    time_offset:
      exposure_time_init: 0.0
      img_time_offset: 0.0
      imu_time_offset: 0.0
    uav:
      gravity_align_en: true
      imu_rate_odom: false
    vio:
      exposure_estimate_en: false
      img_point_cov: 100
      inv_expo_cov: 0.1
      inverse_composition_en: false
      max_iterations: 5
      normal_en: true
      outlier_threshold: 1000
      patch_pyrimid_level: 4
      patch_size: 8
      raycast_en: false
